### ISSUE TITLE
Explain me the output 

### ISSUE THREAD

**Issue by NeerajAvanigadda** [zekaouinoureddine/COVID-19-DETECTION-FROM-X-RAY#1]
Can you explain me the whole code of VGG-19

**Comment by zekaouinoureddine** [comment]
Explaining the entire code can be time-consuming, but I suggest seeking help from [**ChatGPT**](https://chat.openai.com/). Simply provide it with the code cells you're having trouble with as a prompt, and it will provide you with a detailed explanation. Here's an example of how to do it:

**`PROMPT`**:

---

```python
VGG19_model = keras.applications.VGG19(
    input_shape=X_train.shape[1:],
    include_top=False,
    weights="imagenet")
VGG19_model.trainable = False
```

**`ChatGPT ANSWER`**: 

---
This code initializes a pre-trained VGG19 model using Keras Applications, and then sets the model's weights to be non-trainable.

The first line of code creates a new instance of the VGG19 model by calling the **`keras.applications.VGG19()`** function with the following arguments:

* **`input_shape=X_train.shape[1:]`**: This specifies the shape of the input data that the model will accept. **`X_train`** is assumed to be a NumPy array containing the training data, and **`X_train.shape[1:]`** returns a tuple that contains the shape of a single input sample without the batch size.

* **`include_top=False`**: This argument specifies whether to include the top fully connected layers of the model, which are responsible for classifying the input images. By setting **`include_top=False`**, the fully connected layers are excluded, and only the convolutional base of the VGG19 model is used. This is useful when you want to use the pre-trained model as a feature extractor for a different task.

* **`weights="imagenet"`**: This argument specifies the pre-trained weights to load for the model. **`"imagenet"`** refers to the ImageNet dataset, which was used to train the original VGG19 model. By setting **`weights="imagenet"`**, the weights of the pre-trained model will be loaded into the new instance of the model.

The second line of code sets the **`trainable`** attribute of the **`VGG19_model`** object to **`False`**, which means that the weights of the pre-trained model will not be updated during training of the downstream task. This is usually done when using a pre-trained model as a feature extractor since the goal is to keep the learned representations fixed and use them as inputs to a new classifier or regressor. By setting **`trainable`** to **`False`**, the weights of the pre-trained model will be frozen, preventing them from being updated during training of the new model.

---

It's very efficient and I hope it helps you to understand the whole code.
